### ISSUE TITLE
KeyError: 'external_media'

### ISSUE THREAD

**Issue by hidezember** [casouri/weibo2mast#2]
你好~想请教下这个报错的原因…已经重新检查过其他配置应该都没有问题，google了一下相关语法也找不到原因

Traceback (most recent call last):
  File "xpost.py", line 520, in <module>
    records = cross_post(post, mast_dict, config, db)
  File "xpost.py", line 127, in cross_post
    external_media = get_user_option(user_id, 'external_media', config)
  File "xpost.py", line 270, in get_user_option
    return config[option]
KeyError: 'external_media'

**Comment by casouri** [comment]
不好意思，这是文档的疏忽。在`config.json`里加入
```
"external_media": false,
```
这一项应该就可以了。

**Comment by hidezember** [comment]
嗯嗯，感谢反馈，不过貌似还有一些其他的小问题：

Traceback (most recent call last):
  File "xpost.py", line 520, in <module>
    records = cross_post(post, mast_dict, config, db)
  File "xpost.py", line 143, in cross_post
    upload_media(url_list[:max_attatchment])
  File "xpost.py", line 96, in upload_media
    if len(url_list) > max_attatchment:
NameError: name 'max_attatchment' is not defined

我检查了一下：
CONFIG_FILE = 'config.json'
config = get_config(CONFIG_FILE)
max_attatchment = config['max_attachment_count']
照理应该是有define的…
把config['max_attachment_count']直接替换成对应数字也一样报错

**Comment by casouri** [comment]
啊，感谢提醒，我改了一下，现在应该可以了，麻烦你试一试（我最近没在用了，没法测试）。

**Comment by hidezember** [comment]
谢谢谢谢，另外mast也没有define需要补充一下，我自己加上搞定了。
还想请教一下，bot有设置怎么识别新发布的内容，否则是运行一次就全部重新发布一次？
不好意思是python新手，给你添麻烦了，非常感谢你的耐心>_<

**Comment by casouri** [comment]
没事没事，反倒我写出bug真不好意思。bot会保存转过的微博在本地数据库，不会重复转

**Comment by hidezember** [comment]
嗯嗯，我没有其他问题啦。再次谢谢你！
