### ISSUE TITLE
Error：Max retries exceeded with url

### ISSUE THREAD

**Issue by hidezember** [casouri/weibo2mast#3]
Hello不好意思再次打扰了，最近这个同步工具不能使用，接收到的错误消息如下

Could not complete request: HTTPSConnectionPool(host='xxx.com', port=443): Max retries exceeded with url: /api/v1/statuses (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x03F30CA0>: Failed to establish a new connection: [WinError 10060] 由于连接 方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

我感觉好像这个是长毛象站点设置的限制，从客户端无解，不知道是否是我理解的这样，也想请百忙中帮忙一起看看，非常感谢。

**Comment by casouri** [comment]
`host='xxx.com'` 里面的xxx.com是你连接的毛象站点，对吗？如果是的话，看起来是毛象站点拒绝访问了。你试试换一个ip跑？

**Comment by hidezember** [comment]
我挂了代理也不行，估计是毛象站点设置的问题…准备放弃了。谢谢你啦~~

**Comment by hidezember** [comment]
更新一下问题解决方案，要在运行的cmd窗口挂代理，就可以了，我的毛象地址被墙了。之前用clash貌似不能代理cmd运行窗口。问题已解决。谢谢作者~
